application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      codexpect:
        license: Apache-2.0
        actions:
          generic:
            function: actions/generic/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          publish-events:
            function: actions/publish-events/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
              apiKey: $SERVICE_API_KEY
              providerId: acbdaea7-d8a7-4a80-bd1e-355f88c2b779
              eventCode: com.postman.productsold
            annotations:
              require-adobe-auth: true
              final: true
          commerce:
            function: actions/commerce/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
              COMMERCE_BASE_URL: $COMMERCE_BASE_URL
              COMMERCE_CONSUMER_KEY: $COMMERCE_CONSUMER_KEY
              COMMERCE_CONSUMER_SECRET: $COMMERCE_CONSUMER_SECRET
              COMMERCE_ACCESS_TOKEN: $COMMERCE_ACCESS_TOKEN
              COMMERCE_ACCESS_TOKEN_SECRET: $COMMERCE_ACCESS_TOKEN_SECRET
            annotations:
              require-adobe-auth: true
              final: true
